app/models.py
"""
    minesweeper.models
    ~~~~~~~~~~~~~~~~~~~~~~~
    
    Description
    
    :copyright: (c) 2017 by LeCoVi.
    :author: Leandro E. Colombo Viña <colomboleandro at bitson.com.ar>.
    :license: AGPL, see LICENSE for more details.
"""
# Standard lib imports
from random import choice
# Third-party imports
from flask_sqlalchemy import SQLAlchemy
# LeCoVi imports


db = SQLAlchemy()


class GameOverException(Exception):
    pass


class Tile(db.Model):
    """This class will represent each Tile."""
    __tablename__ = 'tiles'

    id = db.Column(db.Integer, primary_key=True, index=True)
    x = db.Column(db.Integer, nullable=False)
    y = db.Column(db.Integer, nullable=False)
    has_mine = db.Column(db.Boolean, default=False, nullable=False)
    is_revealed = db.Column(db.Boolean, default=False, nullable=False)
    is_marked = db.Column(db.Boolean, default=False, nullable=False)
    mines_around = db.Column(db.Integer, default=0, nullable=False)
    board_id = db.Column(db.ForeignKey('boards.id'))


class Board(db.Model):
    """This class will represent the whole Board, a set of class:`Tile`"""

    __tablename__ = 'boards'

    id = db.Column(db.Integer, primary_key=True, index=True)
    width = db.Column(db.Integer, nullable=False, default=20)
    height = db.Column(db.Integer, nullable=False, default=15)
    mines = db.Column(db.Integer, nullable=False, default=30)

    tiles = list()

    @classmethod
    def get_by(cls, board_id):
        board = db.session.query(Board).filter_by(id=board_id).first()
        board.tiles = list()
        for x in range(board.width):
            board.tiles.append(list())
            for y in range(board.height):
                tile = board.get_tile(x=x, y=y)
                board.tiles[x].append(tile)
        return board

    def create_tiles(self):
        for y in range(self.height):
            row = list()
            for x in range(self.width):
                new_tile = Tile(x=x, y=y, board_id=self.id)
                db.session.add(new_tile)
                db.session.commit()
                row.append(new_tile)
            self.tiles.append(row)

    def get_tile(self, x, y):
        return db.session.query(Tile).filter_by(board_id=self.id, x=x,
                                                y=y).first()

    def set_mines(self):
        mines_left = self.mines
        while mines_left > 0:
            random_row = choice(range(self.width))
            random_col = choice(range(self.height))
            tile = self.get_tile(x=random_row, y=random_col)
            if not tile.has_mine:
                tile.has_mine = True
            mines_left -= 1

    def set_mines_around(self):
        for row in self.tiles:
            for tile in row:
                for neighbour in self.get_neighbours(tile=tile):
                    if neighbour.has_mine:
                        tile.mines_around += 1

    def get_neighbours(self, tile):
        neighbours_list = list()
        if tile.y == 0:
            neighbours_list.append(self.get_tile(tile.x, tile.y + 1))
            if tile.x == 0:
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y + 1))
            elif tile.x == self.width - 1:
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y + 1))
            else:
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y + 1))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y + 1))
        elif tile.y == self.height - 1:
            neighbours_list.append(self.get_tile(tile.x, tile.y - 1))
            if tile.x == 0:
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y))
            elif tile.x == self.width - 1:
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y))
            else:
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y))
        else:
            neighbours_list.append(self.get_tile(tile.x, tile.y - 1))
            neighbours_list.append(self.get_tile(tile.x, tile.y + 1))
            if tile.x == 0:
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y + 1))
            elif tile.x == self.width - 1:
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y + 1))
            else:
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y - 1))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y))
                neighbours_list.append(self.get_tile(tile.x - 1, tile.y + 1))
                neighbours_list.append(self.get_tile(tile.x + 1, tile.y + 1))
        return neighbours_list

    def reveal_zone(self, tile):
        neighbours = self.get_neighbours(tile=tile)
        for neighbour in neighbours:
            if not neighbour.is_revealed:
                self.reveal_tile(x=neighbour.x, y=neighbour.y)

    def reveal_tile(self, x, y):
        tile = self.get_tile(x, y)
        if not tile.is_marked and not tile.is_revealed:
            if tile.has_mine:
                raise GameOverException('boom!')
            tile.is_revealed = True
            if tile.mines_around == 0:
                self.reveal_zone(tile)

    def mark(self, x, y):
        tile = self.get_tile(x, y)
        if not tile.is_revealed:
            tile.is_marked = not tile.is_marked

app/__init__.py
"""
    minesweeper
    ~~~~~~~~~~~~~~~~~~~~~~~
    
    Description
    
    :copyright: (c) 2017 by LeCoVi.
    :author: Leandro E. Colombo Viña <colomboleandro at bitson.com.ar>.
    :license: AGPL, see LICENSE for more details.
"""
# Standard lib imports
# Third-party imports
# LeCoVi imports
from .main import app, db

app/main.py
"""
    minesweeper.main
    ~~~~~~~~~~~~~~~~~~~~~~~
    
    Description
    
    :copyright: (c) 2017 by LeCoVi.
    :author: Leandro E. Colombo Viña <colomboleandro at bitson.com.ar>.
    :license: AGPL, see LICENSE for more details.
"""
# Standard lib imports
# Third-party imports
from flask import Flask
# LeCoVi imports
from app.routes import mines
from app.models import db


app = Flask(__name__)
app.config['SECRET_KEY'] = '70p 53cr37'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///minesweeper.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.register_blueprint(mines)
db.init_app(app)

app/routes.py
"""
    minesweeper.routes
    ~~~~~~~~~~~~~~~~~~~~~~~
    
    Description
    
    :copyright: (c) 2017 by LeCoVi.
    :author: Leandro E. Colombo Viña <colomboleandro at bitson.com.ar>.
    :license: AGPL, see LICENSE for more details.
"""
# Standard lib imports
# Third-party imports
from flask import Blueprint, render_template
# LeCoVi imports
from .models import db, Board, GameOverException

mines = Blueprint('mines', __name__)


@mines.route('/')
def index():
    return render_template('index.html')


@mines.route('/new')
def new_game():
    board = Board()
    db.session.add(board)
    db.session.commit()
    board.create_tiles()
    # db.session.commit()
    board.set_mines()
    # db.session.commit()
    board.set_mines_around()
    db.session.commit()
    return render_template('new_game.html', board=board)


@mines.route('/reveal/<int:board_id>/<int:x>/<int:y>')
def reveal(board_id, x, y):
    board = Board.get_by(board_id)
    try:
        board.reveal_tile(x, y)
    except GameOverException:
        return render_template('game_over.html', board=board, x=x, y=y)
    db.session.commit()
    return render_template('game.html', board=board)


@mines.route('/mark/<int:board_id>/<int:x>/<int:y>')
def mark(board_id, x, y):
    board = Board.get_by(board_id)
    board.mark(x, y)
    db.session.commit()
    return render_template('game.html', board=board)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Minesweeper</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

app/templates/game.html
{% extends "base.html" %}
{% block body %}
<h2>Flask Minesweeper New Game</h2>
    <h3>Board ID: {{ board.id }}</h3>
    <table>
    <tbody>
    {%  for row in board.tiles %}
        <tr style="height: 10px">
        {% for tile in row %}
            {% if tile.is_marked %}
            <td style="background-color: darkorchid ; width: 20px" id="{{
                    tile.x }}_{{ tile.y }}">
            {% elif tile.is_revealed %}
            <td style="background-color: bisque; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% else %}
            <td style="background-color: aqua; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% endif %}
            {% if tile.has_mine %}
                *
            {% else %}
                {% if tile.is_revealed and not tile.mines_around == 0 %}
                    {{ tile.mines_around }}
                {% else %}

                {% endif %}
            {% endif %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

app/templates/game_over.html
{% extends "base.html" %}
{% block body %}
<h2>Flask Minesweeper Game Over!</h2>
    <h3>Board ID: {{ board.id }}</h3>
    <table>
    <tbody>
    {%  for row in board.tiles %}
        <tr style="height: 10px">
        {% for tile in row %}
            {% if tile.x == x and tile.y == y %}
            <td style="background-color: darkred; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% elif tile.is_revealed %}
            <td style="background-color: bisque; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% else %}
            <td style="background-color: aqua; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% endif %}
                {% if tile.has_mine %}
                    *
                {% else %}
                    {% if tile.is_revealed and not tile.mines_around == 0 %}
                        {{ tile.mines_around }}
                    {% else %}

                    {% endif %}
                {% endif %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block body %}
<h1>Welcome to Flask Minesweeper</h1>
<a href="{{ url_for('mines.new_game') }}">New Game</a>
{% endblock %}

app/templates/new_game.html
{% extends "base.html" %}
{% block body %}
<h2>Flask Minesweeper New Game</h2>
    <h3>Board ID: {{ board.id }}</h3>
    <table>
    <tbody>
    {%  for row in board.tiles %}
        <tr style="height: 10px">
        {% for tile in row %}
            {% if tile.is_revealed %}
            <td style="background-color: bisque; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% else %}
            <td style="background-color: aqua; width: 20px" id="{{ tile.x
                    }}_{{ tile.y }}">
            {% endif %}
            {% if tile.has_mine %}
                *
            {% else %}
                {% if tile.is_revealed and not tile.mines_around == 0 %}
                    {{ tile.mines_around }}
                {% else %}

                {% endif %}
            {% endif %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}